import { Montserrat , Inter } from 'next/font/google';
import { BasketProvider } from '@/context/BasketContext';
import "./globals.css";
import Header from "@/components/layout/header/Header";
import Footer from '@/components/footer/footer';

const montserrat  = Montserrat({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'], 
  variable: '--font-montserrat', 
});
const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'], 
  variable: '--font-inter', 
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${inter.variable}`}
    >
      <body className="font-inter antialiased">
        <BasketProvider>
          <Header />
          {children}
        </BasketProvider>
        <Footer />
      </body>
    </html>
  );
}
