from settings.admins.hero_admin import HeroSliderAdmin
from settings.admins.Store_Benefits_admin import Store_BenefitsAdmin
from settings.admins.AboutUs_admin import AboutUsModelAdmin
from settings.admins.faq_admin import FAQModelAdmin
from settings.admins.ContactMessage_admin import ContactMessageModelAdmin
from settings.admins.ContactInfo_admin import ContactInfoModelAdmin
from settings.admins.TermsAndConditions_admin import TermsAndConditionsModelAdmin
from settings.admins.ReturnPolicy_admin import ReturnPolicyModelAdmin
