from settings.model.hero_model import HeroSlider
from settings.model.Store_Benefits import Store_Benefits
from settings.model.AboutUs_model import AboutUsModel
from settings.model.faq_model import FAQModel
from settings.model.ContactMessage_model import ContactMessageModel
from settings.model.ContactInfo_model import ContactInfoModel
from settings.model.TermsAndConditions_model import TermsAndConditionsModel
from settings.model.ReturnPolicy_model import ReturnPolicyModel