from settings.serializer.hero_serializer import HeroSliderSerializer
from settings.serializer.Store_Benefits_serializer import Store_BenefitsSerializer
from settings.serializer.about_us_serializer import AboutUsSerializer
from settings.serializer.faq_serializer import FAQSerializer
from settings.serializer.ContactMessage_serializer import ContactMessageSerializer
from settings.serializer.ContactInfo_serializer import ContactInfoSerializer
from settings.serializer.TermsAndConditions_serializer import TermsAndConditionSerializer
from settings.serializer.ReturnPolicy_serializer import ReturnPolicySerializer