# Generated by Django 5.2.9 on 2026-10-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title Brand')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name=' (Slug)')),
                ('logo', models.ImageField(upload_to='brands/%Y/%m/', verbose_name='Brand logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='status active/inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create_at')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دسته\u200cبندی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دسته\u200cبندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/', verbose_name='تصویر دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='اسلاگ (Slug)')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'catagory',
                'verbose_name_plural': 'all catagory',
                'ordering': ['parent__id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name=' (Slug)')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='current image product')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='pirce product')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='discout price')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock inventory')),
                ('is_active', models.BooleanField(default=True, verbose_name='status active/inactive')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='Special Offer')),
                ('is_suggested', models.BooleanField(default=False, verbose_name='suggested system')),
                ('sales_count', models.PositiveIntegerField(default=0, verbose_name='count price')),
                ('visited_count', models.PositiveIntegerField(default=0, verbose_name='count visited')),
                ('short_description', models.TextField(verbose_name='short description')),
                ('full_description', models.TextField(verbose_name='full description')),
                ('whats_in_the_box', models.TextField(blank=True, null=True, verbose_name='whats_in_the_box')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=' create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(max_length=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/image', verbose_name='product image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Gallery',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(max_length=50)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
        ),
    ]
