# Generated by Django 5.2.9 on 2026-10-07 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('history', models.TextField(verbose_name='Our History')),
                ('mission', models.TextField(verbose_name='Our Mission')),
                ('vision', models.TextField(verbose_name='Our Vision')),
                ('values', models.TextField(verbose_name='Core Values')),
                ('why_us', models.TextField(verbose_name='Why Choose Us')),
                ('main_image', models.ImageField(upload_to='about_us/', verbose_name='Main Display Image')),
                ('branch_address', models.TextField(verbose_name='Branch Addresses / Locations')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Page Management',
            },
        ),
        migrations.CreateModel(
            name='ContactInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='WhatsApp Number (e.g., +937xxxxxxx)')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram Username / Link')),
                ('instagram', models.CharField(max_length=150, verbose_name='Instagram Username / Link')),
                ('facebook', models.CharField(max_length=150, verbose_name='Facebook Page Link')),
                ('email', models.EmailField(max_length=150, verbose_name='Shop Support Email')),
                ('address', models.TextField(verbose_name='Physical Shop Address')),
                ('google_map_link', models.URLField(max_length=500, verbose_name='Google Maps Embed Link')),
                ('working_hours', models.CharField(max_length=250, verbose_name='Working Hours (e.g., Sat - Thu: 8:00 AM - 5:00 PM)')),
            ],
            options={
                'verbose_name': 'Shop Contact Info',
                'verbose_name_plural': 'Shop Contact Info Management',
            },
        ),
        migrations.CreateModel(
            name='ContactMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Sender Name')),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must start with 07 and be exactly 9 digits.', regex='^07\\d{8}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read By Admin')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Question Title')),
                ('description', models.TextField(verbose_name='Answer / Description')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'Frequently Asked Questions (FAQ)',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('subtitle', models.TextField(blank=True, null=True, verbose_name='Subtitle')),
                ('image', models.ImageField(upload_to='hero/', verbose_name='Slider Image')),
                ('first_btn_text', models.CharField(default='Shop Now', max_length=50, verbose_name='First Button Text')),
                ('first_btn_url', models.URLField(blank=True, null=True, verbose_name='First Button URL')),
                ('second_btn_text', models.CharField(default='Learn More', max_length=50, verbose_name='Second Button Text')),
                ('second_btn_url', models.URLField(blank=True, null=True, verbose_name='Second Button URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slider',
                'verbose_name_plural': 'Hero Sliders',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnPolicyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Return and Refund Policy', max_length=200, verbose_name='Page Title')),
                ('description', models.TextField(verbose_name='General Description')),
                ('return_conditions', models.TextField(verbose_name='Return Conditions (شرایط مرجوعی)')),
                ('returnable_items', models.TextField(verbose_name='Returnable vs Non-Returnable Items')),
                ('time_limit', models.CharField(max_length=250, verbose_name='Time Limits (e.g., 3 Days from delivery)')),
                ('return_steps', models.TextField(verbose_name='Step-by-Step Return Process')),
                ('warranty_terms', models.TextField(verbose_name='Warranty Terms (شرایط ضمانت)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Return Policy',
                'verbose_name_plural': 'Return Policy Management',
            },
        ),
        migrations.CreateModel(
            name='Store_Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Benefit Title')),
                ('image', models.ImageField(upload_to='benefits/', verbose_name='Benefit Icon/Image')),
            ],
            options={
                'verbose_name': 'Store Benefit',
                'verbose_name_plural': 'Store Benefits',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200, verbose_name='Document Title')),
                ('terms_of_use', models.TextField(verbose_name='Terms of Use (قوانین استفاده عمومی)')),
                ('purchase_terms', models.TextField(verbose_name='Purchase Terms (شرایط خرید)')),
                ('order_rules', models.TextField(verbose_name='Order Rules (مقررات ثبت سفارش)')),
                ('payment_rules', models.TextField(verbose_name='Payment Rules (قوانین پرداخت مالی)')),
                ('shipping_rules', models.TextField(verbose_name='Shipping & Delivery Rules (مقررات ارسال و تحویل)')),
                ('cancellation_terms', models.TextField(verbose_name='Cancellation & Refund Terms (شرایط لغو و استرداد)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions Management',
            },
        ),
    ]
